// import 'rxjs/add/operator/map'; // I dont know what this is, but it was autogenerated when I made the provider.  It does not appear to be necessary


// The provider is for Global variables.
// If you want to add a new global variable, create a new private variable below the platform variable then create accesser modifier methods
// I made this following this stackoverflow page:
// http://stackoverflow.com/questions/34815478/access-key-data-across-entire-app-in-angular-2-ionic-2
export class Globals {
  
  static instance : Globals;
  static isCreating : Boolean = false;

  private platform : string;

  constructor()
  {
    if(!Globals.isCreating)
    {
      throw new Error("Improperly instantiated Globals");
    }
  }

  static getInstance() : Globals
  {
    if(Globals.instance == null)
    {
      Globals.isCreating = true;
      Globals.instance = new Globals();
      Globals.isCreating = false;
    }

    return Globals.instance;
  }

  setPlatform(plat) : void
  {
    this.platform = plat;
  }

  getPlatform() : string
  {
    return this.platform;
  }

}
