// import 'rxjs/add/operator/map'; // I dont know what this is, but it was autogenerated when I made the provider.  It does not appear to be necessary


// The provider is for Settings variables.
// If you want to add a new settings variable, create a new private variable below the platform variable then create accesser modifier methods
// I made this following this stackoverflow page:
// http://stackoverflow.com/questions/34815478/access-key-data-across-entire-app-in-angular-2-ionic-2
export class Settings {
  
  static instance : Settings;
  static isCreating : Boolean = false;

  private platform : string;

  constructor()
  {
    if(!Settings.isCreating)
    {
      throw new Error("Improperly instantiated Settings");
    }
  }

  static getInstance() : Settings
  {
    if(Settings.instance == null)
    {
      Settings.isCreating = true;
      Settings.instance = new Settings();
      Settings.isCreating = false;
    }

    return Settings.instance;
  }

  setPlatform(plat) : void
  {
    this.platform = plat;
  }

  getPlatform() : string
  {
    return this.platform;
  }

}
